name: CD - Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile main.py -n StreamSnatch

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: StreamSnatch
          path: dist/StreamSnatch.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: StreamSnatch

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: StreamSnatch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
